spring:
  datasource:
    url: ${DB_URL}
    username:   ${DB_USR}
    password: ${DB_PWRD}


  jpa:
    database-platform : org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto : none
    properties:
      hibernate.format_sql: true

server:
      port:
          5003

